[project]
name = "atliq-hr-assist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.9.4",
]

[tool.poetry.dependencies]
pydantic = "^2.0"
